#pragma once

#include "lvgl.h"

// autogenerated, do not modify!

class Theme {
  protected:
    const lv_img_dsc_t *ui_img_initscreen2;
    const lv_img_dsc_t *ui_img_miningscreen2;
    const lv_img_dsc_t *ui_img_portalscreen;
    const lv_img_dsc_t *ui_img_btcscreen;
    const lv_img_dsc_t *ui_img_settingsscreen;
    const lv_img_dsc_t *ui_img_splashscreen2;
    const lv_img_dsc_t *ui_img_globalStats;

  public:
    // Getters
    const lv_img_dsc_t *getInitscreen2() const {
        return ui_img_initscreen2;
    }
    const lv_img_dsc_t *getMiningscreen2() const {
        return ui_img_miningscreen2;
    }
    const lv_img_dsc_t *getPortalscreen() const {
        return ui_img_portalscreen;
    }
    const lv_img_dsc_t *getBtcscreen() const {
        return ui_img_btcscreen;
    }
    const lv_img_dsc_t *getSettingsscreen() const {
        return ui_img_settingsscreen;
    }
    const lv_img_dsc_t *getSplashscreen2() const {
        return ui_img_splashscreen2;
    }
    const lv_img_dsc_t *getGlobalstats() const {
        return ui_img_globalStats;
    }

    // Setters
    void setInitscreen2(const lv_img_dsc_t *img) {
        ui_img_initscreen2 = img;
    }
    void setMiningscreen2(const lv_img_dsc_t *img) {
        ui_img_miningscreen2 = img;
    }
    void setPortalscreen(const lv_img_dsc_t *img) {
        ui_img_portalscreen = img;
    }
    void setBtcscreen(const lv_img_dsc_t *img) {
        ui_img_btcscreen = img;
    }
    void setSettingsscreen(const lv_img_dsc_t *img) {
        ui_img_settingsscreen = img;
    }
    void setSplashscreen2(const lv_img_dsc_t *img) {
        ui_img_splashscreen2 = img;
    }
    void setGlobalstats(const lv_img_dsc_t *img) {
        ui_img_globalStats = img;
    }
};

// image files for theme BitfortunOctaxeGamma
LV_IMG_DECLARE(ui_img_BitfortunOctaxeGamma_initscreen2_png);
LV_IMG_DECLARE(ui_img_BitfortunOctaxeGamma_miningscreen2_png);
LV_IMG_DECLARE(ui_img_BitfortunOctaxeGamma_portalscreen_png);
LV_IMG_DECLARE(ui_img_BitfortunOctaxeGamma_btcscreen_png);
LV_IMG_DECLARE(ui_img_BitfortunOctaxeGamma_settingsscreen_png);
LV_IMG_DECLARE(ui_img_BitfortunOctaxeGamma_splashscreen2_png);
LV_IMG_DECLARE(ui_img_BitfortunOctaxeGamma_globalStats_png);

// image files for theme BitfortunQaxePlus
LV_IMG_DECLARE(ui_img_BitfortunQaxePlus_initscreen2_png);
LV_IMG_DECLARE(ui_img_BitfortunQaxePlus_miningscreen2_png);
LV_IMG_DECLARE(ui_img_BitfortunQaxePlus_portalscreen_png);
LV_IMG_DECLARE(ui_img_BitfortunQaxePlus_btcscreen_png);
LV_IMG_DECLARE(ui_img_BitfortunQaxePlus_settingsscreen_png);
LV_IMG_DECLARE(ui_img_BitfortunQaxePlus_splashscreen2_png);
LV_IMG_DECLARE(ui_img_BitfortunQaxePlus_globalStats_png);

// image files for theme BitfortunEko
LV_IMG_DECLARE(ui_img_BitfortunEko_initscreen2_png);
LV_IMG_DECLARE(ui_img_BitfortunEko_miningscreen2_png);
LV_IMG_DECLARE(ui_img_BitfortunEko_portalscreen_png);
LV_IMG_DECLARE(ui_img_BitfortunEko_btcscreen_png);
LV_IMG_DECLARE(ui_img_BitfortunEko_settingsscreen_png);
LV_IMG_DECLARE(ui_img_BitfortunEko_splashscreen2_png);
LV_IMG_DECLARE(ui_img_BitfortunEko_globalStats_png);

// image files for theme BitfortunQaxePlus2
LV_IMG_DECLARE(ui_img_BitfortunQaxePlus2_initscreen2_png);
LV_IMG_DECLARE(ui_img_BitfortunQaxePlus2_miningscreen2_png);
LV_IMG_DECLARE(ui_img_BitfortunQaxePlus2_portalscreen_png);
LV_IMG_DECLARE(ui_img_BitfortunQaxePlus2_btcscreen_png);
LV_IMG_DECLARE(ui_img_BitfortunQaxePlus2_settingsscreen_png);
LV_IMG_DECLARE(ui_img_BitfortunQaxePlus2_splashscreen2_png);
LV_IMG_DECLARE(ui_img_BitfortunQaxePlus2_globalStats_png);

// image files for theme BitfortunAxe
LV_IMG_DECLARE(ui_img_BitfortunAxe_initscreen2_png);
LV_IMG_DECLARE(ui_img_BitfortunAxe_miningscreen2_png);
LV_IMG_DECLARE(ui_img_BitfortunAxe_portalscreen_png);
LV_IMG_DECLARE(ui_img_BitfortunAxe_btcscreen_png);
LV_IMG_DECLARE(ui_img_BitfortunAxe_settingsscreen_png);
LV_IMG_DECLARE(ui_img_BitfortunAxe_splashscreen2_png);
LV_IMG_DECLARE(ui_img_BitfortunAxe_globalStats_png);

// image files for theme BitfortunAxeGamma
LV_IMG_DECLARE(ui_img_BitfortunAxeGamma_initscreen2_png);
LV_IMG_DECLARE(ui_img_BitfortunAxeGamma_miningscreen2_png);
LV_IMG_DECLARE(ui_img_BitfortunAxeGamma_portalscreen_png);
LV_IMG_DECLARE(ui_img_BitfortunAxeGamma_btcscreen_png);
LV_IMG_DECLARE(ui_img_BitfortunAxeGamma_settingsscreen_png);
LV_IMG_DECLARE(ui_img_BitfortunAxeGamma_splashscreen2_png);
LV_IMG_DECLARE(ui_img_BitfortunAxeGamma_globalStats_png);

// image files for theme BitfortunQX
LV_IMG_DECLARE(ui_img_BitfortunQX_initscreen2_png);
LV_IMG_DECLARE(ui_img_BitfortunQX_miningscreen2_png);
LV_IMG_DECLARE(ui_img_BitfortunQX_portalscreen_png);
LV_IMG_DECLARE(ui_img_BitfortunQX_btcscreen_png);
LV_IMG_DECLARE(ui_img_BitfortunQX_settingsscreen_png);
LV_IMG_DECLARE(ui_img_BitfortunQX_splashscreen2_png);
LV_IMG_DECLARE(ui_img_BitfortunQX_globalStats_png);

// image files for theme BitfortunOctaxePlus
LV_IMG_DECLARE(ui_img_BitfortunOctaxePlus_initscreen2_png);
LV_IMG_DECLARE(ui_img_BitfortunOctaxePlus_miningscreen2_png);
LV_IMG_DECLARE(ui_img_BitfortunOctaxePlus_portalscreen_png);
LV_IMG_DECLARE(ui_img_BitfortunOctaxePlus_btcscreen_png);
LV_IMG_DECLARE(ui_img_BitfortunOctaxePlus_settingsscreen_png);
LV_IMG_DECLARE(ui_img_BitfortunOctaxePlus_splashscreen2_png);
LV_IMG_DECLARE(ui_img_BitfortunOctaxePlus_globalStats_png);

// image files for theme Generic
LV_IMG_DECLARE(ui_img_Generic_initscreen2_png);
LV_IMG_DECLARE(ui_img_Generic_miningscreen2_png);
LV_IMG_DECLARE(ui_img_Generic_portalscreen_png);
LV_IMG_DECLARE(ui_img_Generic_btcscreen_png);
LV_IMG_DECLARE(ui_img_Generic_settingsscreen_png);
LV_IMG_DECLARE(ui_img_Generic_splashscreen2_png);
LV_IMG_DECLARE(ui_img_Generic_globalStats_png);

// image files for theme BitfortunHaxeGamma
LV_IMG_DECLARE(ui_img_BitfortunHaxeGamma_initscreen2_png);
LV_IMG_DECLARE(ui_img_BitfortunHaxeGamma_miningscreen2_png);
LV_IMG_DECLARE(ui_img_BitfortunHaxeGamma_portalscreen_png);
LV_IMG_DECLARE(ui_img_BitfortunHaxeGamma_btcscreen_png);
LV_IMG_DECLARE(ui_img_BitfortunHaxeGamma_settingsscreen_png);
LV_IMG_DECLARE(ui_img_BitfortunHaxeGamma_splashscreen2_png);
LV_IMG_DECLARE(ui_img_BitfortunHaxeGamma_globalStats_png);


// class  for theme BitfortunOctaxeGamma
class ThemeBitfortunoctaxegamma : public Theme {
public:
    ThemeBitfortunoctaxegamma() {
        setInitscreen2(&ui_img_BitfortunOctaxeGamma_initscreen2_png);
        setMiningscreen2(&ui_img_BitfortunOctaxeGamma_miningscreen2_png);
        setPortalscreen(&ui_img_BitfortunOctaxeGamma_portalscreen_png);
        setBtcscreen(&ui_img_BitfortunOctaxeGamma_btcscreen_png);
        setSettingsscreen(&ui_img_BitfortunOctaxeGamma_settingsscreen_png);
        setSplashscreen2(&ui_img_BitfortunOctaxeGamma_splashscreen2_png);
        setGlobalstats(&ui_img_BitfortunOctaxeGamma_globalStats_png);
    }
};

// class  for theme BitfortunQaxePlus
class ThemeBitfortunqaxeplus : public Theme {
public:
    ThemeBitfortunqaxeplus() {
        setInitscreen2(&ui_img_BitfortunQaxePlus_initscreen2_png);
        setMiningscreen2(&ui_img_BitfortunQaxePlus_miningscreen2_png);
        setPortalscreen(&ui_img_BitfortunQaxePlus_portalscreen_png);
        setBtcscreen(&ui_img_BitfortunQaxePlus_btcscreen_png);
        setSettingsscreen(&ui_img_BitfortunQaxePlus_settingsscreen_png);
        setSplashscreen2(&ui_img_BitfortunQaxePlus_splashscreen2_png);
        setGlobalstats(&ui_img_BitfortunQaxePlus_globalStats_png);
    }
};

// class  for theme BitfortunEko
class ThemeBitfortuneko : public Theme {
public:
    ThemeBitfortuneko() {
        setInitscreen2(&ui_img_BitfortunEko_initscreen2_png);
        setMiningscreen2(&ui_img_BitfortunEko_miningscreen2_png);
        setPortalscreen(&ui_img_BitfortunEko_portalscreen_png);
        setBtcscreen(&ui_img_BitfortunEko_btcscreen_png);
        setSettingsscreen(&ui_img_BitfortunEko_settingsscreen_png);
        setSplashscreen2(&ui_img_BitfortunEko_splashscreen2_png);
        setGlobalstats(&ui_img_BitfortunEko_globalStats_png);
    }
};

// class  for theme BitfortunQaxePlus2
class ThemeBitfortunqaxeplus2 : public Theme {
public:
    ThemeBitfortunqaxeplus2() {
        setInitscreen2(&ui_img_BitfortunQaxePlus2_initscreen2_png);
        setMiningscreen2(&ui_img_BitfortunQaxePlus2_miningscreen2_png);
        setPortalscreen(&ui_img_BitfortunQaxePlus2_portalscreen_png);
        setBtcscreen(&ui_img_BitfortunQaxePlus2_btcscreen_png);
        setSettingsscreen(&ui_img_BitfortunQaxePlus2_settingsscreen_png);
        setSplashscreen2(&ui_img_BitfortunQaxePlus2_splashscreen2_png);
        setGlobalstats(&ui_img_BitfortunQaxePlus2_globalStats_png);
    }
};

// class  for theme BitfortunAxe
class ThemeBitfortunaxe : public Theme {
public:
    ThemeBitfortunaxe() {
        setInitscreen2(&ui_img_BitfortunAxe_initscreen2_png);
        setMiningscreen2(&ui_img_BitfortunAxe_miningscreen2_png);
        setPortalscreen(&ui_img_BitfortunAxe_portalscreen_png);
        setBtcscreen(&ui_img_BitfortunAxe_btcscreen_png);
        setSettingsscreen(&ui_img_BitfortunAxe_settingsscreen_png);
        setSplashscreen2(&ui_img_BitfortunAxe_splashscreen2_png);
        setGlobalstats(&ui_img_BitfortunAxe_globalStats_png);
    }
};

// class  for theme BitfortunAxeGamma
class ThemeBitfortunaxegamma : public Theme {
public:
    ThemeBitfortunaxegamma() {
        setInitscreen2(&ui_img_BitfortunAxeGamma_initscreen2_png);
        setMiningscreen2(&ui_img_BitfortunAxeGamma_miningscreen2_png);
        setPortalscreen(&ui_img_BitfortunAxeGamma_portalscreen_png);
        setBtcscreen(&ui_img_BitfortunAxeGamma_btcscreen_png);
        setSettingsscreen(&ui_img_BitfortunAxeGamma_settingsscreen_png);
        setSplashscreen2(&ui_img_BitfortunAxeGamma_splashscreen2_png);
        setGlobalstats(&ui_img_BitfortunAxeGamma_globalStats_png);
    }
};

// class  for theme BitfortunQX
class ThemeBitfortunqx : public Theme {
public:
    ThemeBitfortunqx() {
        setInitscreen2(&ui_img_BitfortunQX_initscreen2_png);
        setMiningscreen2(&ui_img_BitfortunQX_miningscreen2_png);
        setPortalscreen(&ui_img_BitfortunQX_portalscreen_png);
        setBtcscreen(&ui_img_BitfortunQX_btcscreen_png);
        setSettingsscreen(&ui_img_BitfortunQX_settingsscreen_png);
        setSplashscreen2(&ui_img_BitfortunQX_splashscreen2_png);
        setGlobalstats(&ui_img_BitfortunQX_globalStats_png);
    }
};

// class  for theme BitfortunOctaxePlus
class ThemeBitfortunoctaxeplus : public Theme {
public:
    ThemeBitfortunoctaxeplus() {
        setInitscreen2(&ui_img_BitfortunOctaxePlus_initscreen2_png);
        setMiningscreen2(&ui_img_BitfortunOctaxePlus_miningscreen2_png);
        setPortalscreen(&ui_img_BitfortunOctaxePlus_portalscreen_png);
        setBtcscreen(&ui_img_BitfortunOctaxePlus_btcscreen_png);
        setSettingsscreen(&ui_img_BitfortunOctaxePlus_settingsscreen_png);
        setSplashscreen2(&ui_img_BitfortunOctaxePlus_splashscreen2_png);
        setGlobalstats(&ui_img_BitfortunOctaxePlus_globalStats_png);
    }
};

// class  for theme Generic
class ThemeGeneric : public Theme {
public:
    ThemeGeneric() {
        setInitscreen2(&ui_img_Generic_initscreen2_png);
        setMiningscreen2(&ui_img_Generic_miningscreen2_png);
        setPortalscreen(&ui_img_Generic_portalscreen_png);
        setBtcscreen(&ui_img_Generic_btcscreen_png);
        setSettingsscreen(&ui_img_Generic_settingsscreen_png);
        setSplashscreen2(&ui_img_Generic_splashscreen2_png);
        setGlobalstats(&ui_img_Generic_globalStats_png);
    }
};

// class  for theme BitfortunHaxeGamma
class ThemeBitfortunhaxegamma : public Theme {
public:
    ThemeBitfortunhaxegamma() {
        setInitscreen2(&ui_img_BitfortunHaxeGamma_initscreen2_png);
        setMiningscreen2(&ui_img_BitfortunHaxeGamma_miningscreen2_png);
        setPortalscreen(&ui_img_BitfortunHaxeGamma_portalscreen_png);
        setBtcscreen(&ui_img_BitfortunHaxeGamma_btcscreen_png);
        setSettingsscreen(&ui_img_BitfortunHaxeGamma_settingsscreen_png);
        setSplashscreen2(&ui_img_BitfortunHaxeGamma_splashscreen2_png);
        setGlobalstats(&ui_img_BitfortunHaxeGamma_globalStats_png);
    }
};

